version: "3.9"

services:
  backend:
    build: ./backend
    container_name: ona_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: ona_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
